// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbpcrdvsjweqkblgjmak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFicGNyZHZzandlcWtibGdqbWFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0OTg0MzUsImV4cCI6MjA2MTA3NDQzNX0.hIEnVFQsLw_IGalAWlnmPA-sXICGDdxtRBTkfoWtcUU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);